import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/widgets";
import AuthProvider from "./AuthProvider";
import JotaiProvider from "./JotaiProvider";
import { LoginDialog } from "@/features";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <JotaiProvider>
          <AuthProvider>
            <div className="relative min-h-svh text-body-1">
              <Header />
              {children}
              <LoginDialog />
            </div>
          </AuthProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
