import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/widgets";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const test = async () => {
    fetch("http://localhost/api/auth/refresh");
  };

  test();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative min-h-svh w-svw">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
