from test.fixtures.asset.test_asset_fixture import (  # noqa: F401 test fixture 사용
    setup_all,
    setup_asset,
    setup_asset_field,
    setup_asset_stock_field,
    setup_current_market_index,
    setup_dividend,
    setup_exchange_rate,
    setup_market_index_daily,
    setup_stock,
    setup_realtime_stock_price,
    setup_stock_daily,
    setup_market_index_minutely_data,
    setup_user,
)
