"""include user foreignkey on stock transactions

Revision ID: 41b71c93800d
Revises: 9724f2949afa
Create Date: 2024-05-07 16:26:27.032360

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41b71c93800d"
down_revision: Union[str, None] = "9724f2949afa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock_transactions", sa.Column("user_id", sa.String(length=36), nullable=False))
    op.create_foreign_key(None, "stock_transactions", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "stock_transactions", type_="foreignkey")
    op.drop_column("stock_transactions", "user_id")
    # ### end Alembic commands ###
