"""include foreignkey on stock transactions

Revision ID: 9724f2949afa
Revises: c0a42760a31a
Create Date: 2024-05-07 16:19:33.940692

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9724f2949afa"
down_revision: Union[str, None] = "c0a42760a31a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock_transactions", sa.Column("stock_id", sa.String(length=36), nullable=False))
    op.create_foreign_key(None, "stock_transactions", "stocks", ["stock_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "stock_transactions", type_="foreignkey")
    op.drop_column("stock_transactions", "stock_id")
    # ### end Alembic commands ###
