"""add stock_code field in stock

Revision ID: c0a42760a31a
Revises: e7ef1263c82d
Create Date: 2024-05-07 16:04:49.575995

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0a42760a31a"
down_revision: Union[str, None] = "e7ef1263c82d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stocks", sa.Column("code", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stocks", "code")
    # ### end Alembic commands ###
