"""change stock field name index > market_index

Revision ID: e7ef1263c82d
Revises: 8b729b8205b3
Create Date: 2024-05-07 15:37:28.483705

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7ef1263c82d"
down_revision: Union[str, None] = "8b729b8205b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stocks", sa.Column("market_index", sa.String(length=255), nullable=False))
    op.drop_column("stocks", "index")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stocks", sa.Column("index", mysql.VARCHAR(length=255), nullable=False))
    op.drop_column("stocks", "market_index")
    # ### end Alembic commands ###
