FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y \
    gcc \
    g++ \
    make \
    wget \
    curl \
    unzip \
    xvfb \
    libxi6 \
    libgconf-2-4 \
    default-jdk \
    libnss3 \
    libxss1 \
    libappindicator1 \
    fonts-liberation \
    gnupg \
    chromium \
    && apt-get clean

RUN CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE) && \
    wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/ && \
    unzip ~/chromedriver_linux64.zip -d ~/ && \
    rm ~/chromedriver_linux64.zip && \
    mv -f ~/chromedriver /usr/local/bin/chromedriver && \
    chmod 0755 /usr/local/bin/chromedriver

RUN pip install poetry
RUN pip install peewee==3.17.5

RUN pip install poetry
COPY pyproject.toml poetry.lock /app/
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root

COPY . /app/

COPY ./app/data/naver/world_market_index_realtime.py /app/task.py

ENV DISPLAY=:99

CMD ["python", "task.py"]
