FROM python:3.11

WORKDIR /app

RUN api-get update && apt-get install -y wget unzip && \
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt install -y ./google-chrome-stable_current_amd64.deb && \
    rm google-chrome-stable_current_amd64.deb && \
    apt-get clean


RUN pip install poetry
RUN pip install peewee==3.17.5

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root

COPY . /app/

COPY ./app/data/naver/world_market_index_realtime.py /app/task.py

CMD ["python", "task.py"]
