FROM python:3.11

WORKDIR /app

# Install necessary dependencies and Chromium/Chromedriver
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    unzip \
    chromium \
    chromium-driver \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcairo2 \
    libcups2 \
    libdrm2 \
    libgbm1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libx11-6 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxrandr2 \
    libxss1 \
    libxtst6 \
    libgbm1 \
    xdg-utils \
    libcurl4 \
    libvulkan1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Verify if chromedriver is installed
RUN apt-get install -y chromium-driver && \
    which chromedriver && \
    chromedriver --version || echo "chromedriver not found or installation failed."

# Install Poetry and Peewee
RUN pip install poetry && \
    pip install peewee==3.17.5

# Copy the project files
COPY pyproject.toml poetry.lock /app/

# Configure Poetry and install dependencies
RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root

# Copy the rest of the project files
COPY . /app/

# Task file
COPY ./app/data/naver/world_market_index_realtime.py /app/task.py

CMD ["python", "task.py"]
