FROM public.ecr.aws/lambda/python:3.11

WORKDIR /app

RUN yum update -y && \
    yum install -y gcc g++ make && \
    yum clean all

RUN pip install poetry
RUN pip install peewee==3.17.5

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root

COPY . /app/

COPY app/data/yahoo/exchange_rate.py /app/lambda.py

CMD ["lambda.lambda_handler"]
